version: '3.8'

services:
  pastries-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  microcks:
    image: quay.io/microcks/microcks-uber:1.11.1
    ports:
      - "8585:8080"
    environment:
      - POSTMAN_RUNNER_URL=http://postman:3000
      - TEST_CALLBACK_URL=http://microcks:8080
  postman:
    image: quay.io/microcks/microcks-postman-runtime:0.6.0
    container_name: microcks-postman-runtime
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      start_period: 5s
      interval: 20s
      timeout: 3s
      retries: 3
